# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

# Mod Properties
mod_version = 1.5.3
maven_group = vt
archives_name = ICL
enabled_platforms = fabric,neoforge,forge
mod_id = icl
mod_name = ICL
mod_description = Designed to improve server performance by periodically removing items from the ground.
mod_authors = VeiTr
mod_license = MIT
mod_sources = https://github.com/VeiTrr/ItemClearLag-ICL
mod_issue_tracker = https://github.com/VeiTrr/ItemClearLag-ICL/issues

# Minecraft properties
minecraft_version = 1.21.6
yarn_mappings = 1.21.6+build.1
# Specify the minimum Minecraft version required to run the mod.
# Else, leave it as 0, and it will default to the major version of the Minecraft version specified above. 1.21.1 -> 1.21
minimum_minecraft_version = 1.21.6

# Dependencies
fabric_api_version = 0.128.2+1.21.6
fabric_loader_version = 0.17.2
forge_version = 1.21.6-56.0.9
neoforge_version = 21.6.20-beta
yarn_mappings_patch_neoforge_version = 1.21+build.4

# Fabric
modmenu_version = 15.0.0

